version: "3.7"
services:
  web_magento:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    expose:
      - "80"
    ports: 
      - "8080:8080"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ../magento2:/var/www/html/
    environment:
      - VIRTUAL_HOST=www.mlpbarreiro.com
    restart: always
    networks: 
      - webproxy
      - magento
    depends_on: 
      - php_magento
  php_magento:
    build:
      context: .
      dockerfile: ./integrator/Dockerfile
      args:
        - WITH_XDEBUG=true
    expose:
      - "9000"
    volumes:
      - ../magento2:/var/www/html/
      - ./integrator/auferma:/auferma
    depends_on:
      - db_magento
    env_file:
      - env
    networks: 
      - magento
  db_magento:
    image: mysql:8.0
    volumes:
      - db_magento-data:/var/lib/mysql
      - ./mysql/magento.cnf:/etc/mysql/conf.d/magento.cnf
    env_file:
      - env
    restart: always
    expose:
      - "3306"
    networks: 
      - magento
  adminer_magento:
    image: adminer
    ports:
      - "8000:8080"
    networks: 
      - magento
      - webproxy
    depends_on: 
      - db_magento
  es01_magento:
    build: 
      context: .
      dockerfile: ./elasticSearch/Dockerfile
    container_name: es01_magento
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es_01_magento:/usr/share/elasticsearch/data
    networks:
      - magento
    expose: 
      - "9200"
    networks: 
      - magento
    depends_on: 
      - db_magento
volumes:
  db_magento-data:
  data_es_01_magento:
networks: 
  magento:
  webproxy: 
    external: true