version: "3.7"
services:
  web_magento:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ../magento2:/var/www/
    links:
      - php_magento
  php_magento:
    build:
      context: .
      dockerfile: ./integrator/Dockerfile
      args:
        - WITH_XDEBUG=true
    ports:
      - "9000:9000"
    volumes:
      - ../magento2:/var/www/
      - ./integrator/auferma:/auferma
    links:
      - db_magento
    env_file:
      - env
  db_magento:
    image: mysql:5.6
    volumes:
      - db_magento-data:/var/lib/mysql/data
    env_file:
      - env
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  db_magento-data: